baseurl: "" # the subpath of your site, e.g. /blog
url: "https://junbrooo.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 5
  sort_field: "date"
  sort_reverse: true
  trail: 1
  page: 1
  total: 0
  previous_label: "Previous"
  next_label: "Next"



# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed